package pt.antares.app.feature.about

data class AppVersion(
    val name: String,
    val title: String,
    val titleEn: String,
    val highlights: List<String>,
    val highlightsEn: List<String>,
) {
    fun title(english: Boolean): String = if (english) titleEn else title
    fun highlights(english: Boolean): List<String> = if (english) highlightsEn else highlights
}

object AppChangelog {

    const val CURRENT = "0.9.18.1"

    val versions: List<AppVersion> = listOf(
        AppVersion(
            name = "0.9.18.1",
            title = "O backup à frente",
            titleEn = "Backup, in plain sight",
            highlights = listOf(
                "**Backup** passou a ter lugar próprio nas Definições, a um toque — estava escondido no fim de «Detalhes e metas»",
                "Sem sincronização, guardar um ficheiro é o único caminho de volta se perderes o telemóvel. Agora dá para encontrar",
            ),
            highlightsEn = listOf(
                "**Backup** now has its own place in Settings, one tap away — it was buried at the bottom of «Details and goals»",
                "With no syncing, saving a file is the only way back if you lose your phone. Now you can find it",
            ),
        ),
        AppVersion(
            name = "0.9.18",
            title = "A app volta a ser um APK",
            titleEn = "The app goes back to being an APK",
            highlights = listOf(
                "**A conta e a sincronização saíram.** Davam problemas a mais, e tudo o que é teu vive neste telemóvel",
                "O backup passou a ser um ficheiro teu: **exportas, guardas onde quiseres, e restauras** — e agora leva as fotos de progresso",
                "Ao restaurar podes **juntar** ao que já tens (fica o mais recente) ou **substituir** tudo",
                "Quando a app fecha sozinha, o motivo fica guardado e podes **partilhá-lo** — antes não deixava rasto nenhum",
                "Dois exercícios com o mesmo nome deixaram de rebentar o detalhe do treino",
                "A app arrancava a ler um megabyte de exercícios **todas as vezes**, mesmo já os tendo",
                "A análise por foto e por texto **fica**; o relatório semanal sai e será refeito de outra forma",
            ),
            highlightsEn = listOf(
                "**The account and syncing are gone.** They caused too much trouble, and everything of yours lives on this phone",
                "Backup is now a file you own: **export it, keep it where you like, restore it** — and it carries your progress photos",
                "When restoring you can **merge** with what you have (most recent wins) or **replace** everything",
                "When the app closes on its own, the reason is saved and you can **share it** — before, it left no trace at all",
                "Two exercises with the same name no longer crash the workout detail",
                "The app was reading a megabyte of exercises on **every single start**, even with them already loaded",
                "Photo and text analysis **stays**; the weekly report goes and will be redone another way",
            ),
        ),
        AppVersion(
            name = "0.9.17.1",
            title = "O que se vê ao instalar",
            titleEn = "What you see on install",
            highlights = listOf(
                "O peso já não aparece com **a unidade duas vezes** no primeiro ecrã",
                "Quem usa libras deixou de ver quilos no cartão do peso — e o número passou a ser o certo",
                "Os campos de números abrem o **teclado de números**, sem ter de procurar o «?123»",
                "O teclado deixou de tapar os botões — em toda a app, não só onde deu para reparar",
                "Em inglês, um dia por registar já não diz «1 days»",
                "**Modo demonstração** no Admin: enche a app com dois anos de uma pessoa inventada, e apaga-os outra vez",
            ),
            highlightsEn = listOf(
                "Weight no longer shows **the unit twice** on the very first screen",
                "If you use pounds you no longer see kilos on the weight card — and the number is right now",
                "Number fields open the **number keyboard**, with no hunt for «?123»",
                "The keyboard no longer covers the buttons — everywhere in the app, not only where it was noticed",
                "In English, one unlogged day no longer reads «1 days»",
                "**Demo mode** in Admin: fills the app with two years of an invented person, and takes them back out",
            ),
        ),
        AppVersion(
            name = "0.9.17",
            title = "Entrar na conta",
            titleEn = "Signing in",
            highlights = listOf(
                "**Já dá para entrar com o Google** — e trazer o que tinhas noutro telemóvel",
                "Entrar e ligar deixaram de ser a mesma coisa: ligar guarda esta conta, entrar vai buscar outra",
                "Ao entrares, os teus dados são restaurados **antes** de a app abrir, com o progresso à vista",
                "Se houver dados dos dois lados, a app pergunta — com os dois números à frente — e nunca decide sozinha",
                "**A sincronização passou a ser grátis**, para toda a gente",
                "O Health Connect estava mudo no telemóvel por falta de permissões declaradas — corrigido",
                "Uma edição feita durante a sincronização já não pode perder-se",
                "A app deixou de ser minificada: menos uma forma de partir sem avisar",
            ),
            highlightsEn = listOf(
                "**You can sign in with Google now** — and bring over what you had on another phone",
                "Signing in and linking are no longer the same thing: linking keeps this account, signing in fetches another",
                "When you sign in, your data is restored **before** the app opens, with the progress in view",
                "If there is data on both sides the app asks — both numbers in front of you — and never decides alone",
                "**Syncing is now free**, for everyone",
                "Health Connect was mute on the phone because permissions were never declared — fixed",
                "An edit made while syncing can no longer be lost",
                "The app is no longer minified: one less way to break without warning",
            ),
        ),
        AppVersion(
            name = "0.9.16.4",
            title = "A rede por baixo",
            titleEn = "The net underneath",
            highlights = listOf(
                "As novidades desta lista mostravam **asteriscos** em cru — agora são negrito a sério",
                "E passam a existir em inglês, não só em português",
                "Abrir a app deixou de falar com o Health Connect antes de alguém lho pedir",
                "Abrir o Diário deixou de ler a tabela de referências que só o painel usa",
                "**Uma edição feita enquanto a sincronização estava a decorrer podia nunca subir** — corrigido",
                "Rótulos americanos com vitamina A ou D em UI entravam com o valor errado",
                "Em gravidez e amamentação a app deixa de propor défice",
                "Os dois ecrãs que mais usas passaram a ter testes automáticos",
            ),
            highlightsEn = listOf(
                "The notes in this list showed raw **asterisks** — now they are actually bold",
                "And they exist in English, not only in Portuguese",
                "Opening the app no longer talks to Health Connect before you ask it to",
                "Opening the Diary no longer loads the reference table only the panel uses",
                "**An edit made while a sync was in flight could fail to ever upload** — fixed",
                "US labels declaring vitamin A or D in IU were stored with the wrong value",
                "During pregnancy and breastfeeding the app no longer proposes a deficit",
                "The two screens you use most now have automated tests",
            ),
        ),
        AppVersion(
            name = "0.9.16.3",
            title = "O pente fino",
            titleEn = "The fine comb",
            highlights = listOf(
                "Uma versão sem funcionalidades novas: leu-se a app de uma ponta à outra à procura do que estava errado",
                "**Apagar uma pesagem e voltar a pesar-se no mesmo dia deixava de guardar** — sem erro, sem aviso. Corrigido, e o mesmo valia para as medições e para o relatório do coach",
                "A água somava ao valor que tinhas mandado apagar; agora recomeça do zero",
                "**O ecrã do ciclo não abria** — faltava uma ligação interna que nunca ninguém tinha exercitado",
                "A exportação dos teus dados deixava de fora o ciclo, as fotos e as pesquisas. Agora leva tudo o que é teu",
                "A pesquisa online podia ficar a rodar para sempre numa rede fraca; passou a desistir e a dizer-te",
                "A app só tinha acesso à internet por herança da biblioteca de mapas — agora pede-o por si",
                "Os recordes de força deixam de dizer «0 kg» quando a série é longa de mais para estimar",
            ),
            highlightsEn = listOf(
                "A release with no new features: the app was read end to end looking for what was wrong",
                "**Deleting a weigh-in and weighing again the same day saved nothing** — no error, no warning. Fixed, and the same applied to measurements and the coach report",
                "Water was adding to the value you had asked to delete; it now restarts from zero",
                "**The cycle screen would not open** — an internal wiring nobody had ever exercised",
                "Exporting your data left out the cycle, the photos and the searches. It now takes everything that is yours",
                "Online search could spin forever on a weak network; it now gives up and tells you",
                "The app only had internet access inherited from the maps library — it now asks for it itself",
                "Strength records no longer say \"0 kg\" when the set is too long to estimate from",
            ),
        ),
        AppVersion(
            name = "0.9.16.2",
            title = "A app tira-se do caminho",
            titleEn = "The app gets out of the way",
            highlights = listOf(
                "Uma caixa só, no topo do Hoje e do Diário: escreve, dita, fotografa ou lê o código",
                "**Outra vez** — repete num toque a última vez que comeste essa refeição",
                "Os teus 20 alimentos e as tuas 5 refeições à cabeça da pesquisa, e sugestões desde a 1.ª letra",
                "**Só as calorias**, para os dias em que registar com detalhe não vai acontecer",
                "A app aprende a tua dose habitual de cada alimento — e nunca inventa números",
                "Marca vários alimentos e regista-os todos de uma vez",
                "Lê vários códigos de barras seguidos, sem sair da câmara",
                "O widget passou a registar: água e «outra vez», sem abrir a app",
                "O 5.º separador é agora **o teu perfil**; as definições estão na engrenagem",
                "O progresso ganhou um número grande, escolha de período e três perguntas",
                "As fotos saíram de trás de um botão: vês a primeira contra a mais recente",
                "**Esta semana** — o orçamento deixou de fechar contas à meia-noite",
                "O que te falta hoje leva-te aos alimentos que to dão",
                "Copia uma refeição de qualquer dia, e move ou apaga a refeição inteira",
                "Dá às refeições os nomes que tu usas",
                "As perguntas iniciais passaram de onze para nove",
                "A composição corporal passa mesmo a ser escrita no Health Connect",
                "Um cartão do teu progresso para partilhar — números, nunca fotos",
                "Tema claro e leitor de ecrã varridos a sério, com testes que os mantêm assim",
            ),
            highlightsEn = listOf(
                "One box, at the top of Today and the Diary: type, dictate, photograph or scan",
                "**Again** — repeat the last time you ate that meal, in one tap",
                "Your top 20 foods and top 5 meals up front, and suggestions from the first letter",
                "**Calories only**, for the days when logging in detail is not going to happen",
                "The app learns your usual portion of each food — and never invents numbers",
                "Tick several foods and log them all at once",
                "Scan several barcodes in a row without leaving the camera",
                "The widget now logs: water and \"again\", without opening the app",
                "The 5th tab is now **your profile**; settings live in the gear icon",
                "Progress gained one big number, a time range and three questions",
                "Photos came out from behind a button: see the first against the latest",
                "**This week** — the budget stopped settling accounts at midnight",
                "What you are short of today takes you to the foods that provide it",
                "Copy a meal from any day, and move or delete a whole meal",
                "Give meals the names you actually use",
                "The opening questions went from eleven to nine",
                "Body composition is now genuinely written to Health Connect",
                "A progress card to share — numbers, never photos",
                "Light theme and screen reader properly swept, with tests that keep them that way",
            ),
        ),
        AppVersion(
            name = "0.9.16.1",
            title = "O que ficou por fazer",
            titleEn = "What was left undone",
            highlights = listOf(
                "O **Mais** voltou ao sítio — o Progresso passou para o fim do Hoje",
                "A tendência do peso deixou de ser igual ao peso: agora conta os dias, não as pesagens",
                "O gráfico do peso ganhou datas no eixo — três meses parados desenham-se como três meses",
                "Podes registar o peso de ontem, e o histórico já distingue anos",
                "Alimentos repetidos entre o nosso catálogo e o do INSA: fica o do INSA",
                "Fotos de progresso, **só neste telemóvel** — nem para servidor, nem para a cópia de segurança",
                "Registo do ciclo, também só no telemóvel, para a balança deixar de confundir retenção com gordura",
                "Braço, coxa e peito passam mesmo a ficar guardados ao longo do tempo",
                "A app diz-te como tens comido — factos; os conselhos só se os ligares nas definições",
                "Referências de nutrientes na gravidez, amamentação e pós-menopausa",
                "As perguntas iniciais passam a incluir as unidades e o peso que queres atingir",
                "«Já estiveste aqui» e a linha do tempo dos objetivos passam a funcionar mesmo",
                "A cópia de segurança do Android deixou de levar tudo — e foi testada a sério",
            ),
            highlightsEn = listOf(
                "**More** went back where it was — Progress moved to the end of Today",
                "The weight trend stopped matching the weight: it now counts days, not weigh-ins",
                "The weight chart gained dates on its axis — three idle months now look like three months",
                "You can log yesterday's weight, and the history now tells years apart",
                "Foods duplicated between our catalogue and the INSA one: the INSA entry stays",
                "Progress photos, **on this phone only** — not to the server, not to the backup",
                "Cycle logging, also phone-only, so the scale stops mistaking retention for fat",
                "Arm, thigh and chest are now genuinely kept over time",
                "The app tells you how you have been eating — facts; advice only if you enable it",
                "Nutrient references for pregnancy, breastfeeding and post-menopause",
                "The opening questions now include units and the weight you want to reach",
                "\"You have been here\" and the goal timeline now actually work",
                "The Android backup stopped taking everything — and was properly tested",
            ),
        ),
        AppVersion(
            name = "0.9.16",
            title = "A app lembra-se",
            titleEn = "The app remembers",
            highlights = listOf(
                "Separador **Progresso** novo — o único ecrã que olha para trás",
                "Gráfico do peso a sério, com escala, tendência e o teu peso-alvo marcado",
                "Mapa de consistência: doze semanas de dias registados, de relance",
                "Este mês contra o anterior, sem comparar meses que não dão para comparar",
                "A linha do tempo dos teus objetivos — quando os puseste e quando lá chegaste",
                "Marcos: 30 dias registados, 5 kg de mudança, factuais e sem elogios vazios",
                "**1376 alimentos portugueses do INSA**, medidos em Portugal, todos com micros",
                "Gordura trans passa a aparecer, com os valores medidos da tabela nacional",
                "«Já estiveste aqui»: o mesmo peso, mas o corpo já não é o mesmo",
                "A app escreve a composição corporal no Health Connect, além de a ler",
                "Braço, coxa e peito juntam-se à cintura nas medições",
            ),
            highlightsEn = listOf(
                "New **Progress** tab — the one screen that looks backwards",
                "A real weight chart, with scale, trend and your goal weight marked",
                "Consistency map: twelve weeks of logged days, at a glance",
                "This month against the last, without comparing months that cannot be compared",
                "The timeline of your goals — when you set them and when you got there",
                "Milestones: 30 days logged, 5 kg of change, factual and without empty praise",
                "**1376 Portuguese foods from INSA**, measured in Portugal, all with micronutrients",
                "Trans fat now appears, with measured values from the national table",
                "\"You have been here\": the same weight, but the body is no longer the same",
                "The app writes body composition to Health Connect as well as reading it",
                "Arm, thigh and chest join the waist in measurements",
            ),
        ),
        AppVersion(
            name = "0.9.15.1",
            title = "Perfil completo",
            titleEn = "The profile, completed",
            highlights = listOf(
                "Quando a balança não responde há semanas, a app pára de cortar e explica porquê",
                "Pausa de dieta: comer à manutenção umas semanas em vez de cortar mais",
                "«Mostra-me a conta» — a aritmética da tua meta, aberta, com os teus números",
                "Chegar ao peso-alvo deixa de te manter em défice — a app propõe manutenção",
                "Um peso-alvo abaixo do saudável para a tua altura passa a ser dito",
                "A composição corporal ganha histórico: vê a gordura e a cintura ao longo do tempo",
                "A tua balança inteligente preenche a % de gordura sozinha, pelo Health Connect",
                "Recomposição como objetivo, para quem quer perder gordura e ganhar músculo",
                "Régua do IMC a sério, FFMI, e a manutenção sempre à vista",
                "A retenção do ciclo dá 1 a 3 kg — a app diz isso em vez de te deixar pensar que é gordura",
                "A partir dos 65 o mínimo de proteína sobe; abaixo dos 18 o ritmo é mais conservador",
                "A app explica como te pesares, e pergunta quando um peso parece erro de escrita",
                "Altura em pés e polegadas para quem usa imperial",
            ),
            highlightsEn = listOf(
                "When the scale has not moved for weeks, the app stops cutting and explains why",
                "Diet break: eat at maintenance for a few weeks instead of cutting further",
                "\"Show me the maths\" — the arithmetic of your target, open, with your numbers",
                "Reaching your goal weight no longer keeps you in a deficit — the app proposes maintenance",
                "A goal weight below what is healthy for your height is now said out loud",
                "Body composition gained history: see fat and waist over time",
                "Your smart scale fills in body fat by itself, through Health Connect",
                "Recomposition as a goal, for losing fat and gaining muscle at once",
                "A proper BMI scale, FFMI, and maintenance always in view",
                "Cycle retention is 1 to 3 kg — the app says so instead of letting you think it is fat",
                "From 65 the protein minimum rises; under 18 the rate is more conservative",
                "The app explains how to weigh yourself, and asks when a weight looks like a typo",
                "Height in feet and inches for anyone using imperial",
            ),
        ),
        AppVersion(
            name = "0.9.15",
            title = "Perfil e Metas",
            titleEn = "Profile and targets",
            highlights = listOf(
                "Ecrã novo: Perfil e Saúde — o teu corpo, o teu rumo e de onde vem cada número",
                "O nível de atividade passou a contar o dia sem treinos; antes o exercício contava duas vezes",
                "Composição corporal: sabes o valor, estimas por medidas ou pelo IMC — e a app diz sempre qual foi",
                "Com a tua % de gordura, a meta é calculada pela massa magra em vez do peso todo",
                "O ritmo escolhe-se em kg por semana; as calorias são a consequência, com zona segura à vista",
                "Peso-alvo com data prevista pelo teu ritmo real — e a app cala-se quando os dados não chegam",
                "Quando a tua meta muda, a app diz o número velho, o novo e porquê",
            ),
            highlightsEn = listOf(
                "New screen: Profile and Health — your body, your direction, and where each number comes from",
                "Activity level now describes the day without workouts; exercise used to count twice",
                "Body composition: you know the value, estimate from measurements or from BMI — and the app always says which",
                "With your body fat known, the target is computed from lean mass instead of total weight",
                "Rate is chosen in kg per week; the calories are the consequence, with the safe zone in view",
                "Goal weight with a date projected from your real rate — and the app stays quiet when the data is not enough",
                "When your target changes, the app gives the old number, the new one and why",
            ),
        ),
        AppVersion(
            name = "0.9.14.1",
            title = "Nutrição — a continuação",
            titleEn = "Nutrition — continued",
            highlights = listOf(
                "A fibra e o sódio mostram a % da referência diária, como as vitaminas",
                "B5, fósforo, manganês e iodo deixaram de aparecer sem referência",
                "Novos no catálogo: colesterol, gorduras mono e poliinsaturadas, água e álcool",
                "Aviso quando o sódio ou a gordura saturada passam a referência do dia",
                "Toca num registo do diário para veres tudo o que a app guardou dele",
            ),
            highlightsEn = listOf(
                "Fibre and sodium show their percentage of the daily reference, like the vitamins",
                "B5, phosphorus, manganese and iodine no longer appear without a reference",
                "New in the catalogue: cholesterol, mono- and polyunsaturated fat, water and alcohol",
                "A warning when sodium or saturated fat pass the day's reference",
                "Tap a diary entry to see everything the app stored about it",
            ),
        ),
    )
}
